before_script:
  - cp spec/dummy/config/database.peakflow.yml spec/dummy/config/database.yml
  - bundle exec rails db:create db:schema:load
rvm: true
services:
  postgres:
    environment:
      POSTGRES_USER: "peakflow"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "peakflow_test"
    expose:
      - 5432
    image: postgres:11.4
script:
  - bundle exec rspec
  - bundle exec rubocop
